/**
 * Товары раздела «Розы» с публичной витрины (на 2025–2026 г.):
 * https://florista.tomsk.ru/roses
 */
(function () {
  const u = (path) => "https://florista.tomsk.ru" + (path[0] === "/" ? path : "/" + path);

  const P = {
    "oc-255": {
      name: "Букет из 25 роз",
      price: 6750,
      priceStr: "6 750 ₽",
      desc: "Сборка из каталога — уточняйте сорт, длину и упаковку в заказе.",
      imageUrl: u("image/cache/catalog/roses/5A46FF72-C459-49CA-8653-A15F5A5D37BA-228x228.jpeg"),
      productUrl: u("roses?product_id=255"),
      img: 2,
      badge: "Хит",
    },
    "oc-297": {
      name: "Пионовидная Роза «PINK X-PRESSION»",
      price: 300,
      priceStr: "300 ₽",
      desc: "Пионовидная роза — в букет или отдельно, поштучно в заказе.",
      imageUrl: u("image/cache/catalog/roses/43835DF8-47DD-4994-AD80-D2EC074DD3A5-228x228.jpeg"),
      productUrl: u("roses?product_id=297"),
      img: 3,
      badge: null,
    },
    "oc-267": {
      name: "Пионовидная Роза Кантри Блюз",
      price: 300,
      priceStr: "300 ₽",
      desc: "Поштучно, подбор по сезону — как на витрине магазина в Томске.",
      imageUrl: u("image/cache/catalog/roses/66F193EE-ECFD-4E04-8E03-5D1A32A18163-228x228.jpeg"),
      productUrl: u("roses?product_id=267"),
      img: 1,
      badge: null,
    },
    "oc-182": {
      name: "Роза «deep purple»",
      price: 300,
      priceStr: "300 ₽",
      desc: "Эквадорская роза, сорт deep purple.",
      imageUrl: u("image/cache/catalog/roses/rose_deep_purple-228x228.jpg"),
      productUrl: u("rose-deep-purple"),
      img: 1,
      badge: null,
    },
    "oc-50": {
      name: "Роза Амстердам",
      price: 250,
      priceStr: "250 ₽",
      desc: "Классическая букетная роза, подойдёт в микс и в моно.",
      imageUrl: u("image/cache/catalog/roses/amsterdam-228x228.jpg"),
      productUrl: u("amsterdam"),
      img: 1,
      badge: null,
    },
    "oc-51": {
      name: "Роза Ангжамент",
      price: 250,
      priceStr: "250 ₽",
      desc: "Нежно-розовый тон, романтичный акцент.",
      imageUrl: u("image/cache/catalog/roses/anghament-228x228.jpg"),
      productUrl: u("angzhament"),
      img: 1,
      badge: null,
    },
    "oc-52": {
      name: "Роза Карусель",
      price: 300,
      priceStr: "300 ₽",
      desc: "Сорт для выразительных букетов и композиции.",
      imageUrl: u("image/cache/catalog/roses/carousel-228x228.jpg"),
      productUrl: u("carousel"),
      img: 2,
      badge: null,
    },
    "oc-153": {
      name: "Роза Микс",
      price: 250,
      priceStr: "250 ₽",
      desc: "Яркий сет оттенков, как в каталоге.",
      imageUrl: u("image/cache/catalog/roses/mix-228x228.jpg"),
      productUrl: u("rose_mix"),
      img: 1,
      badge: null,
    },
    "oc-53": {
      name: "Роза Мондеаль",
      price: 250,
      priceStr: "250 ₽",
      desc: "Белые розы: искренность и спокойная элегантность.",
      imageUrl: u("image/cache/catalog/roses/mondeal-228x228.jpg"),
      productUrl: u("mondeal"),
      img: 4,
      badge: null,
    },
    "oc-54": {
      name: "Роза Мохана",
      price: 250,
      priceStr: "250 ₽",
      desc: "Букетная, для моно и сборных вариантов.",
      imageUrl: u("image/cache/catalog/roses/mohana-228x228.jpg"),
      productUrl: u("mohana"),
      img: 1,
      badge: null,
    },
    "oc-55": {
      name: "Роза Сантана",
      price: 250,
      priceStr: "250 ₽",
      desc: "Стабильно популярный сорт, как в разделе «Розы» на сайте.",
      imageUrl: u("image/cache/catalog/roses/santana-228x228.jpg"),
      productUrl: u("rose_santana"),
      img: 1,
      badge: null,
    },
    "oc-56": {
      name: "Роза Свитнесс",
      price: 250,
      priceStr: "250 ₽",
      desc: "Сладкое звучание оттенка, хорошо в паре с гортензией.",
      imageUrl: u("image/cache/catalog/roses/sweetness-228x228.jpg"),
      productUrl: u("svitness"),
      img: 1,
      badge: null,
    },
    "oc-57": {
      name: "Роза Топаз",
      price: 250,
      priceStr: "250 ₽",
      desc: "Сорт для контрастных букетов с зеленью и эвкалиптом.",
      imageUrl: u("image/cache/catalog/roses/topaz-228x228.jpg"),
      productUrl: u("topaz"),
      img: 1,
      badge: null,
    },
    "oc-58": {
      name: "Роза Фридом",
      price: 300,
      priceStr: "300 ₽",
      desc: "Алые розы — сильный акцент, классика повода «я люблю».",
      imageUrl: u("image/cache/catalog/roses/freedom-228x228.jpg"),
      productUrl: u("rose_freedom"),
      img: 1,
      badge: null,
    },
    "oc-206": {
      name: "Роза Фридом, 70 см",
      price: 600,
      priceStr: "600 ₽",
      desc: "Удлинённый стебель — крупнее жест, премиальнее силуэт.",
      imageUrl: u("image/cache/catalog/bouquets/roses/15rose-228x228.jpg"),
      productUrl: u("rose70sm"),
      img: 1,
      badge: "Премиум",
    },
    "oc-59": {
      name: "Роза Хай Меджик",
      price: 250,
      priceStr: "250 ₽",
      desc: "Сорт с устойчивым характером и насыщенной палитрой.",
      imageUrl: u("image/cache/catalog/roses/high_magic-228x228.jpg"),
      productUrl: u("high_magic"),
      img: 1,
      badge: null,
    },
    "oc-60": {
      name: "Роза Черри",
      price: 250,
      priceStr: "250 ₽",
      desc: "Сочные оттенки, смотрится в монобукетах и коробах.",
      imageUrl: u("image/cache/catalog/roses/cherry-228x228.jpg"),
      productUrl: u("cherry"),
      img: 1,
      badge: null,
    },
  };

  window.FLORISTA_ROSE_PRODUCTS = P;
  window.FLORISTA_ROSES = Object.fromEntries(
    Object.entries(P).map(([k, v]) => [
      k,
      { name: v.name, price: v.price, img: v.img, imageUrl: v.imageUrl },
    ]),
  );
})();
